<?php

namespace App\Models;


/**
 * Class On
 * @package App\Models
 * @mixin \Eloquent
 */
class On extends Model
{

    protected $table    = 'on';
    protected $fillable = [
        'name',
        'value',
        'desc',
    ];

    protected static function boot()
    {
        parent::boot(); // TODO: Change the autogenerated stub
    }
}
